rules:
  bem-depth:
    - 0
    - max-depth: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  leading-zero: 0
  no-vendor-prefixes:
    - 0
  nesting-depth:
    - 2
    - max-depth: 5
